c_compiler_version:
  - 5.4
cxx_compiler_version:
  - 5.4
cudatoolkit:
  - 9.0
cudnn:
  - 7.1
python:
  - 2.7
  - 3.5
  - 3.6
r_implementation:
  - r-base
  - mro-base  # [not osx and not linux32 and not win32]
