{% set name = "r-xgboost-gpu" %}
{% set version = "0.72" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/dmlc/xgboost
  # corresponds to 0.72 tag
  git_tag: 1214081f994c3798703a035419aafb84716c3cba
  patches:
    # xgboost patches
    - 0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch
    - 0002-Fix-R-package-PKGROOT.patch
    - 0003-Fix-R-package-mingw-w64-compiler-flags-remove-m64.patch
    - 0004-Fix-configure-check-for-OpenMP-on-macOS.patch
    - 0005-Add-ADD_-FLAGS-to-end-of-commandlines.patch
    # dmlc-core patches
    # TODO: verify that this is no longer necessary
    #- 0001-Do-not-define-fopen64-as-std-fopen-on-32-bit-mingw-w.patch

build:
  skip: true  # [win32 or linux32]
  rpaths:
    - lib/R/lib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake                       # [linux]
    - git                         # [linux]
    - m2-git                      # [win]
    - make                        # [linux]
    - posix                       # [win]
    {% if r_implementation == "mro-base" %}
    - rtools                      # [win]
    {% else %}
    - m2w64-toolchain             # [win]
    {% endif %}
  host:
    # GPU requirements
    - cudatoolkit {{ cudatoolkit }}*
    - {{ r_implementation }}
    - r-matrix
    - r-data.table
    - r-magrittr
    - r-stringi
    - r-knitr
  run:
    - cudatoolkit {{ cudatoolkit }}*
    - {{ r_implementation }}
    - r-matrix
    - r-data.table
    - r-magrittr
    - r-stringi

test:
  files:
    - test-r-xgboost.r
  commands:
    - Rscript test-r-xgboost.r
