# GPU variant, builds GPU variants of libxgboost and py-xgboost packages
{% set name = "xgboost" %}
{% set version = "0.72" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/dmlc/xgboost
  # corresponds to 0.72 tag
  git_tag: 1214081f994c3798703a035419aafb84716c3cba
  patches:
    # xgboost patches
    - 0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch
    - 0002-Fix-R-package-PKGROOT.patch
    - 0003-Fix-R-package-mingw-w64-compiler-flags-remove-m64.patch
    - 0004-Fix-configure-check-for-OpenMP-on-macOS.patch
    - 0005-Add-ADD_-FLAGS-to-end-of-commandlines.patch
    # dmlc-core patches
    # TODO: verify that this is no longer necessary
    #- 0001-Do-not-define-fopen64-as-std-fopen-on-32-bit-mingw-w.patch

build:
  skip: true  # [not linux64 and not win64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - git
    - make
  host:
    - cudatoolkit {{ cudatoolkit }}*
    - cudnn {{ cudnn }}*

outputs:
  - name: libxgboost
    script: install-libxgboost.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - git
        - make
      host:
        - cudatoolkit {{ cudatoolkit }}*
        - cudnn {{ cudnn }}*
      run:
        - cudatoolkit {{ cudatoolkit }}*
        - cudnn {{ cudnn }}*

  - name: py-xgboost
    script: install-py-xgboost.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('libxgboost', exact=True) }}
        - python
        - setuptools
      run:
        - {{ pin_subpackage('libxgboost', exact=True) }}
        - python
        - numpy
        - scipy
        - scikit-learn
    test:
      script: test-py-xgboost.py
